//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.CLUB.APPLICATION.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRS.CLUB.APPLICATION.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompanying fee.
        /// </summary>
        public static string Accompanying_fee {
            get {
                return ResourceManager.GetString("Accompanying fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Add_New {
            get {
                return ResourceManager.GetString("Add New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Payment.
        /// </summary>
        public static string Admin_Payment {
            get {
                return ResourceManager.GetString("Admin Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the language?.
        /// </summary>
        public static string Are_you_sure_you_want_to_change_the_language {
            get {
                return ResourceManager.GetString("Are you sure you want to change the language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Details.
        /// </summary>
        public static string Basic_Details {
            get {
                return ResourceManager.GetString("Basic Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string Basic_Information {
            get {
                return ResourceManager.GetString("Basic Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string Birth_date {
            get {
                return ResourceManager.GetString("Birth date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Request.
        /// </summary>
        public static string Booking_Request {
            get {
                return ResourceManager.GetString("Booking Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building &amp; Room No..
        /// </summary>
        public static string Building_and_Room_No {
            get {
                return ResourceManager.GetString("Building and Room No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Logo.
        /// </summary>
        public static string Choose_Banner_logo {
            get {
                return ResourceManager.GetString("Choose_Banner_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Images.
        /// </summary>
        public static string Choose_Images {
            get {
                return ResourceManager.GetString("Choose Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Logo.
        /// </summary>
        public static string Choose_Logo {
            get {
                return ResourceManager.GetString("Choose Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        public static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Amount.
        /// </summary>
        public static string Club_Amount {
            get {
                return ResourceManager.GetString("Club Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Info.
        /// </summary>
        public static string Club_Info {
            get {
                return ResourceManager.GetString("Club Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Location.
        /// </summary>
        public static string Club_Location {
            get {
                return ResourceManager.GetString("Club Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Management.
        /// </summary>
        public static string Club_Management {
            get {
                return ResourceManager.GetString("Club Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your club detail informations..
        /// </summary>
        public static string Club_Management_Supporting_Texts {
            get {
                return ResourceManager.GetString("Club Management Supporting Texts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Name.
        /// </summary>
        public static string Club_Name {
            get {
                return ResourceManager.GetString("Club Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours (From).
        /// </summary>
        public static string Club_Opening_Time {
            get {
                return ResourceManager.GetString("Club Opening Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Profile.
        /// </summary>
        public static string Club_Profile {
            get {
                return ResourceManager.GetString("Club Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Verification Status.
        /// </summary>
        public static string Club_Verification_Status {
            get {
                return ResourceManager.GetString("Club Verification Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Name (English).
        /// </summary>
        public static string ClubNameEng {
            get {
                return ResourceManager.GetString("ClubNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Name (Katakana).
        /// </summary>
        public static string ClubNameKatakana {
            get {
                return ResourceManager.GetString("ClubNameKatakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string Confirm_New_Password {
            get {
                return ResourceManager.GetString("Confirm New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constellation Group.
        /// </summary>
        public static string Constellation_Group {
            get {
                return ResourceManager.GetString("Constellation Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Picture.
        /// </summary>
        public static string Cover_Picture {
            get {
                return ResourceManager.GetString("Cover Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Password.
        /// </summary>
        public static string Create_New_Password {
            get {
                return ResourceManager.GetString("Create New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created_On.
        /// </summary>
        public static string Created_On {
            get {
                return ResourceManager.GetString("Created On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string Current_Password {
            get {
                return ResourceManager.GetString("Current Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Date.
        /// </summary>
        public static string Custom_Date {
            get {
                return ResourceManager.GetString("Custom Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name (Nickname).
        /// </summary>
        public static string Customer_Name__Nickname_ {
            get {
                return ResourceManager.GetString("Customer Name (Nickname)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Validation.
        /// </summary>
        public static string Customer_Validation {
            get {
                return ResourceManager.GetString("Customer Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Customer’s Reservation by entering OTP code that has been sent to your mobile number..
        /// </summary>
        public static string CustomerValidationMsg {
            get {
                return ResourceManager.GetString("CustomerValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string Date_of_Birth {
            get {
                return ResourceManager.GetString("Date of Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day After Tomorrow.
        /// </summary>
        public static string Day_After_Tomorrow {
            get {
                return ResourceManager.GetString("Day After Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string Display_Order {
            get {
                return ResourceManager.GetString("Display Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Page.
        /// </summary>
        public static string Display_Page {
            get {
                return ResourceManager.GetString("Display Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email_Address {
            get {
                return ResourceManager.GetString("Email Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter building &amp; room no..
        /// </summary>
        public static string Enter_building___room_no_ {
            get {
                return ResourceManager.GetString("Enter building & room no.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Event Title.
        /// </summary>
        public static string Enter_Event_Title {
            get {
                return ResourceManager.GetString("Enter Event Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP from Customer.
        /// </summary>
        public static string Enter_OTP_from_Customer {
            get {
                return ResourceManager.GetString("Enter OTP from Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter street.
        /// </summary>
        public static string Enter_street {
            get {
                return ResourceManager.GetString("Enter street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your club credentials to continue..
        /// </summary>
        public static string Enter_your_club_credentials_to_continue_ {
            get {
                return ResourceManager.GetString("Enter your club credentials to continue.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        public static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Management.
        /// </summary>
        public static string Event_Management {
            get {
                return ResourceManager.GetString("Event Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Title.
        /// </summary>
        public static string Event_Title {
            get {
                return ResourceManager.GetString("Event Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF.
        /// </summary>
        public static string Export_Pdf {
            get {
                return ResourceManager.GetString("Export Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        public static string Filter_By {
            get {
                return ResourceManager.GetString("Filter_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Former Job.
        /// </summary>
        public static string Former_Job {
            get {
                return ResourceManager.GetString("Former Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string From_date {
            get {
                return ResourceManager.GetString("From_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Management.
        /// </summary>
        public static string Gallery_Management {
            get {
                return ResourceManager.GetString("Gallery Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery/Banner.
        /// </summary>
        public static string Gallery_or_Banner {
            get {
                return ResourceManager.GetString("Gallery or Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your gallery..
        /// </summary>
        public static string GallerySupportMsg {
            get {
                return ResourceManager.GetString("GallerySupportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Maps.
        /// </summary>
        public static string Google_Maps {
            get {
                return ResourceManager.GetString("Google Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        public static string Grand_Total {
            get {
                return ResourceManager.GetString("Grand Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string Group_Name {
            get {
                return ResourceManager.GetString("Group Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Host info.
        /// </summary>
        public static string Hide_Host_info {
            get {
                return ResourceManager.GetString("Hide Host info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Info.
        /// </summary>
        public static string Host_Info {
            get {
                return ResourceManager.GetString("Host Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage host recommendation orders..
        /// </summary>
        public static string Host_List_Supporting_Text {
            get {
                return ResourceManager.GetString("Host List Supporting Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Management.
        /// </summary>
        public static string Host_Management {
            get {
                return ResourceManager.GetString("Host Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string Host_Name {
            get {
                return ResourceManager.GetString("Host Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Image should be in HEIF format and Maximum file size is  5 MB..
        /// </summary>
        public static string ImageNote {
            get {
                return ResourceManager.GetString("ImageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Preference.
        /// </summary>
        public static string Language_Preference {
            get {
                return ResourceManager.GetString("Language Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your system language preference..
        /// </summary>
        public static string Language_Preference_Supporting_Text {
            get {
                return ResourceManager.GetString("Language Preference Supporting Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language updated successfully.
        /// </summary>
        public static string Language_updated_successfully {
            get {
                return ResourceManager.GetString("Language updated successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Entry Syokai.
        /// </summary>
        public static string Last_Entry_Time {
            get {
                return ResourceManager.GetString("Last Entry Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Order Time.
        /// </summary>
        public static string Last_Order_Time {
            get {
                return ResourceManager.GetString("Last Order Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated on.
        /// </summary>
        public static string Last_updated_on {
            get {
                return ResourceManager.GetString("Last updated on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquor Strength.
        /// </summary>
        public static string LiquorStrength {
            get {
                return ResourceManager.GetString("LiquorStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Hoslog.
        /// </summary>
        public static string loginMsg {
            get {
                return ResourceManager.GetString("loginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username/Phone Number.
        /// </summary>
        public static string LoginPlaceholderForUsername {
            get {
                return ResourceManager.GetString("LoginPlaceholderForUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string Main_Menu {
            get {
                return ResourceManager.GetString("Main Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage club booking request.
        /// </summary>
        public static string Manage_club_booking_request {
            get {
                return ResourceManager.GetString("Manage club booking request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Event.
        /// </summary>
        public static string Manage_Event {
            get {
                return ResourceManager.GetString("Manage Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Gallery.
        /// </summary>
        public static string Manage_Gallery {
            get {
                return ResourceManager.GetString("Manage Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Host.
        /// </summary>
        public static string Manage_Host {
            get {
                return ResourceManager.GetString("Manage Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage host recommendation orders..
        /// </summary>
        public static string Manage_host_recommendation_orders_ {
            get {
                return ResourceManager.GetString("Manage host recommendation orders.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your profile informations.
        /// </summary>
        public static string Manage_your_profile_informations {
            get {
                return ResourceManager.GetString("Manage_your_profile_informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is 16 characters.
        /// </summary>
        public static string Maximum_length_is_16_characters {
            get {
                return ResourceManager.GetString("Maximum length is 16 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length is 8 characters.
        /// </summary>
        public static string Minimum_length_is_8_characters {
            get {
                return ResourceManager.GetString("Minimum length is 8 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event.
        /// </summary>
        public static string New_Event {
            get {
                return ResourceManager.GetString("New Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Host.
        /// </summary>
        public static string New_Host {
            get {
                return ResourceManager.GetString("New Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string New_Request {
            get {
                return ResourceManager.GetString("New Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Choosen.
        /// </summary>
        public static string No_File_Choosen {
            get {
                return ResourceManager.GetString("No File Choosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Hosts.
        /// </summary>
        public static string No_of_Hosts {
            get {
                return ResourceManager.GetString("No of Hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Show.
        /// </summary>
        public static string No_of_Show {
            get {
                return ResourceManager.GetString("No of Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomination fee.
        /// </summary>
        public static string Nomination_fee {
            get {
                return ResourceManager.GetString("Nomination fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-site nomination.
        /// </summary>
        public static string On_site_nomination {
            get {
                return ResourceManager.GetString("On-site nomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our top booked hosts..
        /// </summary>
        public static string Our_top_booked_hosts {
            get {
                return ResourceManager.GetString("Our top booked hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage request admin for top recommendations..
        /// </summary>
        public static string Page_List_Supporting_Text {
            get {
                return ResourceManager.GetString("Page List Supporting Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payement Status.
        /// </summary>
        public static string Payement_Status {
            get {
                return ResourceManager.GetString("Payement Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paymemt Ledgers.
        /// </summary>
        public static string Paymemt_Ledgers {
            get {
                return ResourceManager.GetString("Paymemt Ledgers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information regarding specific dates..
        /// </summary>
        public static string Payment_Ledger_Supporting_Text {
            get {
                return ResourceManager.GetString("Payment Ledger Supporting Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Logs.
        /// </summary>
        public static string Payment_Logs {
            get {
                return ResourceManager.GetString("Payment Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Management.
        /// </summary>
        public static string Payment_Management {
            get {
                return ResourceManager.GetString("Payment Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Payments.
        /// </summary>
        public static string Payment_Management_Supporting_Text {
            get {
                return ResourceManager.GetString("Payment Management Supporting Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string Payment_Method {
            get {
                return ResourceManager.GetString("Payment Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Option.
        /// </summary>
        public static string Payment_Option {
            get {
                return ResourceManager.GetString("Payment Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Payments.
        /// </summary>
        public static string Pending_Payments {
            get {
                return ResourceManager.GetString("Pending Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Price.
        /// </summary>
        public static string Plan_Price {
            get {
                return ResourceManager.GetString("Plan Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string Postal_code {
            get {
                return ResourceManager.GetString("Postal code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefecture.
        /// </summary>
        public static string Prefecture {
            get {
                return ResourceManager.GetString("Prefecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Occupation.
        /// </summary>
        public static string PreviousOccupation {
            get {
                return ResourceManager.GetString("PreviousOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string Profile_Picture {
            get {
                return ResourceManager.GetString("Profile Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        public static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation List.
        /// </summary>
        public static string Recommendation_List {
            get {
                return ResourceManager.GetString("Recommendation List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage request admin for top recommendations..
        /// </summary>
        public static string Recommendation_List_Supporting_Text {
            get {
                return ResourceManager.GetString("Recommendation List Supporting Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation Request.
        /// </summary>
        public static string Recommendation_Request {
            get {
                return ResourceManager.GetString("Recommendation Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to request for the Recommendation?.
        /// </summary>
        public static string Recommendation_Request_Confirm_Text {
            get {
                return ResourceManager.GetString("Recommendation Request Confirm Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Admin for Top recommendations..
        /// </summary>
        public static string Recommendation_Request_Supporting_Text {
            get {
                return ResourceManager.GetString("Recommendation Request Supporting Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Price 1 hour.
        /// </summary>
        public static string Regular_Price_1_hour {
            get {
                return ResourceManager.GetString("Regular Price 1 hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to accept the Booking Request?.
        /// </summary>
        public static string RequestAcceptMsz {
            get {
                return ResourceManager.GetString("RequestAcceptMsz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Date.
        /// </summary>
        public static string Requested_Date {
            get {
                return ResourceManager.GetString("Requested Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reject the Booking Request?.
        /// </summary>
        public static string RequestRejectMsz {
            get {
                return ResourceManager.GetString("RequestRejectMsz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Details.
        /// </summary>
        public static string Reservation_Details {
            get {
                return ResourceManager.GetString("Reservation Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Ledger.
        /// </summary>
        public static string Reservation_Ledger {
            get {
                return ResourceManager.GetString("Reservation Ledger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the reservation, including the date, time, and duration of the reservation..
        /// </summary>
        public static string Reservation_Ledger_Supporting_Texts {
            get {
                return ResourceManager.GetString("Reservation Ledger Supporting Texts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Number.
        /// </summary>
        public static string Reservation_Number {
            get {
                return ResourceManager.GetString("Reservation Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage club’s and their host’s review &amp; ratings..
        /// </summary>
        public static string Review_and_rating_supporting_text {
            get {
                return ResourceManager.GetString("Review and rating supporting text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review &amp; Ratings.
        /// </summary>
        public static string Review_and_Ratings {
            get {
                return ResourceManager.GetString("Review and Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed On.
        /// </summary>
        public static string Reviewed_On {
            get {
                return ResourceManager.GetString("Reviewed On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.N.
        /// </summary>
        public static string S_N {
            get {
                return ResourceManager.GetString("S.N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Report.
        /// </summary>
        public static string Sales_Report {
            get {
                return ResourceManager.GetString("Sales Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Save_Changes {
            get {
                return ResourceManager.GetString("Save Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Management.
        /// </summary>
        public static string Schedule_Management {
            get {
                return ResourceManager.GetString("Schedule Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Status.
        /// </summary>
        public static string Schedule_Status {
            get {
                return ResourceManager.GetString("Schedule Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your profile security.
        /// </summary>
        public static string SecuritySupportMsz {
            get {
                return ResourceManager.GetString("SecuritySupportMsz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Hosts.
        /// </summary>
        public static string See_All_Hosts {
            get {
                return ResourceManager.GetString("See All Hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string Select_Language {
            get {
                return ResourceManager.GetString("Select Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up a new password to login.
        /// </summary>
        public static string Set_up_a_new_password_to_login {
            get {
                return ResourceManager.GetString("Set up a new password to login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Links .
        /// </summary>
        public static string Social_Links {
            get {
                return ResourceManager.GetString("Social Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiktok.
        /// </summary>
        public static string Tiktok {
            get {
                return ResourceManager.GetString("Tiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        public static string Title_Placeholder {
            get {
                return ResourceManager.GetString("Title Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string To_date {
            get {
                return ResourceManager.GetString("To_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Bookings.
        /// </summary>
        public static string Todays_Bookings {
            get {
                return ResourceManager.GetString("Todays Bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Ranking Hosts.
        /// </summary>
        public static string Top_Ranking_Hosts {
            get {
                return ResourceManager.GetString("Top Ranking Hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bookings.
        /// </summary>
        public static string Total_Bookings {
            get {
                return ResourceManager.GetString("Total Bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Commission.
        /// </summary>
        public static string Total_Commission {
            get {
                return ResourceManager.GetString("Total Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hosts.
        /// </summary>
        public static string Total_Hosts {
            get {
                return ResourceManager.GetString("Total Hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        public static string Total_Sales {
            get {
                return ResourceManager.GetString("Total Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total service tax &amp; consumption tax.
        /// </summary>
        public static string Total_service_tax_and_consumption_tax {
            get {
                return ResourceManager.GetString("Total service tax and consumption tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visitors.
        /// </summary>
        public static string Total_Visitors {
            get {
                return ResourceManager.GetString("Total Visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        public static string Update_Profile {
            get {
                return ResourceManager.GetString("Update Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        public static string Updated_Date {
            get {
                return ResourceManager.GetString("Updated Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated On.
        /// </summary>
        public static string Updated_On {
            get {
                return ResourceManager.GetString("Updated On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save this Privilege?.
        /// </summary>
        public static string UpdateProfileAlert {
            get {
                return ResourceManager.GetString("UpdateProfileAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        public static string User_Info {
            get {
                return ResourceManager.GetString("User Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Phone Number.
        /// </summary>
        public static string Username_Phone_Number {
            get {
                return ResourceManager.GetString("Username/Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various drinks.
        /// </summary>
        public static string Various_drinks {
            get {
                return ResourceManager.GetString("Various drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string View_all {
            get {
                return ResourceManager.GetString("View all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Calendar.
        /// </summary>
        public static string View_Calendar {
            get {
                return ResourceManager.GetString("View Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Date.
        /// </summary>
        public static string Visit_Date {
            get {
                return ResourceManager.GetString("Visit Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Time.
        /// </summary>
        public static string Visit_Time {
            get {
                return ResourceManager.GetString("Visit Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Hoslog.
        /// </summary>
        public static string Welcome_to_Hoslog {
            get {
                return ResourceManager.GetString("Welcome to Hoslog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours (From).
        /// </summary>
        public static string Working_Hours_From {
            get {
                return ResourceManager.GetString("Working Hours From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours (To).
        /// </summary>
        public static string Working_Hours_To {
            get {
                return ResourceManager.GetString("Working Hours To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string Your_Message {
            get {
                return ResourceManager.GetString("Your Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. Description about club.
        /// </summary>
        public static string Your_Message_Placeholder {
            get {
                return ResourceManager.GetString("Your Message Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 〒173-0015.
        /// </summary>
        public static string ZipCode_placeholder {
            get {
                return ResourceManager.GetString("ZipCode_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zodiac.
        /// </summary>
        public static string zodiac {
            get {
                return ResourceManager.GetString("zodiac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zodiac Sign.
        /// </summary>
        public static string Zodiac_Sign {
            get {
                return ResourceManager.GetString("Zodiac Sign", resourceCulture);
            }
        }
    }
}
